const fs = require('fs');
const path = require('path');
const { PDFDocument, rgb, StandardFonts } = require('pdf-lib');
const Report = require('../models/Report');
const ReportSchedule = require('../models/ReportSchedule');
const Invoice = require('../models/Invoice');
const ExtractedData = require('../models/ExtractedData');
const { getTeamUserIds } = require('../utils/tenant');

// Helper to format currency
const formatCurrency = (amount) => {
  return new Intl.NumberFormat('en-US', { style: 'currency', currency: 'USD' }).format(amount || 0);
};

// Helper to format date
const formatDate = (dateStr) => {
  if (!dateStr) return 'N/A';
  const d = new Date(dateStr);
  return d.toLocaleDateString('en-US', { year: 'numeric', month: 'short', day: 'numeric' });
};

// Generate PDF using pdf-lib
async function generatePDFReport({ title, type, dateRange, dataList, creatorName }) {
  const pdfDoc = await PDFDocument.create();
  const font = await pdfDoc.embedFont(StandardFonts.Helvetica);
  const boldFont = await pdfDoc.embedFont(StandardFonts.HelveticaBold);
  const monoFont = await pdfDoc.embedFont(StandardFonts.Courier);

  // Colors
  const textWhite = rgb(1, 1, 1);
  const darkBg = rgb(0.1, 0.04, 0.04); // #1A0A0B equivalent approx
  const mainRed = rgb(0.56, 0.11, 0.23); // #8E1B3A
  const lightRed = rgb(0.85, 0.56, 0.56); // #D98F8F
  const darkGray = rgb(0.3, 0.3, 0.3);
  const lightGray = rgb(0.95, 0.95, 0.95);
  const borderGray = rgb(0.8, 0.8, 0.8);

  // Setup page (A4 dimensions: 595.28 x 841.89 points)
  const page = pdfDoc.addPage([595, 842]);
  const { width, height } = page.getSize();
  
  // Background header banner
  page.drawRectangle({
    x: 0,
    y: height - 120,
    width: width,
    height: 120,
    color: darkBg
  });

  // Top accent line
  page.drawRectangle({
    x: 0,
    y: height - 10,
    width: width,
    height: 10,
    color: mainRed
  });

  // Brand Name / Header Text
  page.drawText('AURA FINANCE', {
    x: 40,
    y: height - 50,
    size: 20,
    font: boldFont,
    color: lightRed
  });

  page.drawText('INTELLIGENCE REPORT ENGINE', {
    x: 40,
    y: height - 70,
    size: 10,
    font: font,
    color: textWhite
  });

  // Report details on the right
  page.drawText(`Date: ${formatDate(new Date())}`, {
    x: width - 200,
    y: height - 40,
    size: 9,
    font: font,
    color: textWhite
  });

  page.drawText(`Type: ${type}`, {
    x: width - 200,
    y: height - 55,
    size: 9,
    font: font,
    color: textWhite
  });

  page.drawText(`Period: ${dateRange}`, {
    x: width - 200,
    y: height - 70,
    size: 9,
    font: font,
    color: textWhite
  });

  page.drawText(`Generated By: ${creatorName}`, {
    x: width - 200,
    y: height - 85,
    size: 9,
    font: font,
    color: textWhite
  });

  // Document Title
  page.drawText(title, {
    x: 40,
    y: height - 170,
    size: 22,
    font: boldFont,
    color: darkBg
  });

  // Executive Summary Card
  const totalAmount = dataList.reduce((sum, item) => sum + (item.totalAmount || 0), 0);
  const totalTax = dataList.reduce((sum, item) => sum + (item.tvaAmount || 0), 0);
  const invoiceCount = dataList.length;

  page.drawRectangle({
    x: 40,
    y: height - 260,
    width: width - 80,
    height: 65,
    color: lightGray,
    borderColor: borderGray,
    borderWidth: 1
  });

  page.drawText('EXECUTIVE SUMMARY', {
    x: 55,
    y: height - 212,
    size: 10,
    font: boldFont,
    color: mainRed
  });

  // Three stats columns
  page.drawText('Total Documents', { x: 55, y: height - 232, size: 9, font, color: darkGray });
  page.drawText(invoiceCount.toString(), { x: 55, y: height - 250, size: 14, font: boldFont, color: darkBg });

  page.drawText('Total Expenses (Gross)', { x: 220, y: height - 232, size: 9, font, color: darkGray });
  page.drawText(formatCurrency(totalAmount), { x: 220, y: height - 250, size: 14, font: boldFont, color: darkBg });

  page.drawText('Total Tax (TVA)', { x: 420, y: height - 232, size: 9, font, color: darkGray });
  page.drawText(formatCurrency(totalTax), { x: 420, y: height - 250, size: 14, font: boldFont, color: darkBg });

  // Main Section Header
  page.drawText('DETAILED BREAKDOWN', {
    x: 40,
    y: height - 295,
    size: 12,
    font: boldFont,
    color: darkBg
  });

  // Drawing the Table
  let yPosition = height - 325;
  const tableHeaders = ['Date', 'Invoice #', 'Supplier', 'Status', 'Uploader', 'Action By', 'Total'];
  const headerXPositions = [40, 90, 150, 260, 330, 420, 500];

  // Header Row Background
  page.drawRectangle({
    x: 40,
    y: yPosition - 5,
    width: width - 80,
    height: 22,
    color: darkBg
  });

  // Table Headers Text
  tableHeaders.forEach((header, index) => {
    page.drawText(header, {
      x: headerXPositions[index],
      y: yPosition,
      size: 9,
      font: boldFont,
      color: textWhite
    });
  });

  yPosition -= 22;

  // Table rows (Cap to fit one page for simplicity, but handle if we overflow slightly)
  const maxRows = 16;
  const displayRows = dataList.slice(0, maxRows);

  displayRows.forEach((item, rowIndex) => {
    // Zebra striping
    if (rowIndex % 2 === 1) {
      page.drawRectangle({
        x: 40,
        y: yPosition - 5,
        width: width - 80,
        height: 20,
        color: lightGray
      });
    }

    // Border line bottom of row
    page.drawLine({
      start: { x: 40, y: yPosition - 5 },
      end: { x: width - 40, y: yPosition - 5 },
      thickness: 0.5,
      color: borderGray
    });

    const docDate = formatDate(item.date || item.createdAt);
    const invoiceNum = (item.invoiceNumber || 'N/A').substring(0, 10);
    const supplier = (item.companyName || 'Unknown').substring(0, 18);
    const status = item.status || 'UNKNOWN';
    const uploader = (item.uploadedBy || 'N/A').substring(0, 15);
    const actionBy = (item.actionBy || 'N/A').substring(0, 15);
    const gross = formatCurrency(item.totalAmount);

    page.drawText(docDate, { x: headerXPositions[0], y: yPosition, size: 8, font });
    page.drawText(invoiceNum, { x: headerXPositions[1], y: yPosition, size: 8, font: monoFont });
    page.drawText(supplier, { x: headerXPositions[2], y: yPosition, size: 8, font });
    page.drawText(status, { x: headerXPositions[3], y: yPosition, size: 8, font });
    page.drawText(uploader, { x: headerXPositions[4], y: yPosition, size: 8, font });
    page.drawText(actionBy, { x: headerXPositions[5], y: yPosition, size: 8, font });
    page.drawText(gross, { x: headerXPositions[6], y: yPosition, size: 8, font: boldFont });

    yPosition -= 20;
  });

  if (dataList.length > maxRows) {
    page.drawText(`* Showing first ${maxRows} of ${invoiceCount} items. Export to CSV for full list.`, {
      x: 40,
      y: yPosition - 10,
      size: 8,
      font: font,
      color: darkGray
    });
  }

  // Draw Footer
  page.drawLine({
    start: { x: 40, y: 50 },
    end: { x: width - 40, y: 50 },
    thickness: 1,
    color: darkBg
  });

  page.drawText('Aura Finance - Automated Auditing & Financial intelligence platform', {
    x: 40,
    y: 35,
    size: 7,
    font: font,
    color: darkGray
  });

  page.drawText('Confidential', {
    x: width - 85,
    y: 35,
    size: 7,
    font: boldFont,
    color: mainRed
  });

  return await pdfDoc.save();
}

// Generate CSV data from list
function generateCSVReport({ type, dateRange, dataList }) {
  let csvContent = `Aura Finance Intelligence Report\n`;
  csvContent += `Report Type,${type}\n`;
  csvContent += `Date Range,${dateRange}\n`;
  csvContent += `Generated At,${new Date().toISOString()}\n\n`;

  if (type === 'Tax Compliance Audit') {
    csvContent += `Date,Invoice Number,Supplier,Status,Uploaded By,Action By,Matricule Fiscal,HT Amount,TVA (Tax),Timbre,Total Amount\n`;
    dataList.forEach(item => {
      csvContent += `"${formatDate(item.date || item.createdAt)}","${item.invoiceNumber || 'N/A'}","${item.companyName || 'Unknown'}","${item.status || 'UNKNOWN'}","${item.uploadedBy || 'N/A'}","${item.actionBy || 'N/A'}","${item.matriculeFiscal || 'N/A'}",${item.totalHT || 0},${item.tvaAmount || 0},${item.timbre || 0},${item.totalAmount || 0}\n`;
    });
  } else if (type === 'Vendor Spend Analysis') {
    // Aggregate by supplier
    const suppliers = {};
    dataList.forEach(item => {
      const name = item.companyName || 'Unknown Vendor';
      if (!suppliers[name]) {
        suppliers[name] = { total: 0, count: 0, tax: 0 };
      }
      suppliers[name].total += (item.totalAmount || 0);
      suppliers[name].tax += (item.tvaAmount || 0);
      suppliers[name].count += 1;
    });

    csvContent += `Vendor/Supplier Name,Invoice Count,Total Spend,TVA Paid,Average Spend\n`;
    Object.keys(suppliers).forEach(name => {
      const s = suppliers[name];
      csvContent += `"${name}",${s.count},${s.total},${s.tax},${(s.total / s.count).toFixed(2)}\n`;
    });
  } else if (type === 'AI Extraction Accuracy') {
    csvContent += `Date,Invoice Number,Supplier,Overall Confidence,Manual Edit,Last Edited By\n`;
    dataList.forEach(item => {
      const confidence = item.confidenceScores?.overall || item.confidence || 0.85;
      csvContent += `"${formatDate(item.date || item.createdAt)}","${item.invoiceNumber || 'N/A'}","${item.companyName || 'Unknown'}",${(confidence * 100).toFixed(1)}%,${item.isManualEntry ? 'Yes' : 'No'},"${item.lastEditedBy || 'N/A'}"\n`;
    });
  } else {
    // Default/Profit & Loss
    csvContent += `Date,Invoice Number,Supplier,Status,Uploaded By,Action By,Tax Amount,Total Amount\n`;
    dataList.forEach(item => {
      csvContent += `"${formatDate(item.date || item.createdAt)}","${item.invoiceNumber || 'N/A'}","${item.companyName || 'Unknown'}","${item.status || 'UNKNOWN'}","${item.uploadedBy || 'N/A'}","${item.actionBy || 'N/A'}",${item.tvaAmount || 0},${item.totalAmount || 0}\n`;
    });
  }

  return csvContent;
}

// ──────────────────────────────────────────────
// Controllers
// ──────────────────────────────────────────────

// Fetch all generated reports
const getReports = async (req, res, next) => {
  try {
    const { role, _id: userId } = req.user;
    let filter = {};
    if (role === 'ADMIN' || req.user.approvalLevel >= 2) {
      const teamUserIds = await getTeamUserIds(req.user);
      filter.userId = { $in: teamUserIds };
    } else {
      filter.userId = userId;
    }
    const reports = await Report.find(filter).sort({ createdAt: -1 });
    res.json({ success: true, data: reports });
  } catch (error) {
    next(error);
  }
};

// Generate new report
const generateReport = async (req, res, next) => {
  try {
    const { type, dateRange, format } = req.body;
    const { _id: userId, name: creatorName } = req.user;

    if (!type || !dateRange || !format) {
      return res.status(400).json({ success: false, message: 'Type, date range, and format are required.' });
    }

    // 1. Parse Date Range
    let year = new Date().getFullYear();
    const yearMatch = dateRange.match(/\b(20\d{2})\b/);
    if (yearMatch) {
      year = parseInt(yearMatch[1]);
    }

    let startDate, endDate;
    if (dateRange.includes('to')) {
      const parts = dateRange.split('to').map(s => s.trim());
      startDate = new Date(parts[0]);
      endDate = new Date(parts[1]);
      endDate.setHours(23, 59, 59, 999);
    } else if (dateRange.includes('Q1')) {
      startDate = new Date(year, 0, 1);
      endDate = new Date(year, 2, 31, 23, 59, 59, 999);
    } else if (dateRange.includes('Q2')) {
      startDate = new Date(year, 3, 1);
      endDate = new Date(year, 5, 30, 23, 59, 59, 999);
    } else if (dateRange.includes('Q3') || dateRange.includes('Jul - Sep')) {
      startDate = new Date(year, 6, 1);
      endDate = new Date(year, 8, 30, 23, 59, 59, 999);
    } else if (dateRange.includes('Q4')) {
      startDate = new Date(year, 9, 1);
      endDate = new Date(year, 11, 31, 23, 59, 59, 999);
    } else {
      // Default full year
      startDate = new Date(year, 0, 1);
      endDate = new Date(year, 11, 31, 23, 59, 59, 999);
    }

    // 2. Fetch approved invoices for the organization
    const { role } = req.user;
    let invoiceFilter = {
      createdAt: { $gte: startDate, $lte: endDate }
    };
    
    if (role === 'ADMIN' || req.user.approvalLevel >= 2) {
      const teamUserIds = await getTeamUserIds(req.user);
      invoiceFilter.userId = { $in: teamUserIds };
    } else {
      invoiceFilter.userId = userId;
    }

    const invoices = await Invoice.find(invoiceFilter).populate('userId', 'name email');
    const invoiceIds = invoices.map(i => i._id);

    const dataList = await ExtractedData.find({
      invoiceId: { $in: invoiceIds }
    }).sort({ date: 1, createdAt: 1 }).lean();

    // Fetch AuditLogs for these invoices to find who approved/rejected
    const AuditLog = require('../models/AuditLog');
    const auditLogs = await AuditLog.find({
      entityId: { $in: invoiceIds },
      action: { $in: ['INVOICE_APPROVE', 'INVOICE_REJECT'] }
    }).populate('userId', 'name').sort({ timestamp: -1 }).lean();

    const actionByMap = {};
    auditLogs.forEach(log => {
      if (!actionByMap[log.entityId.toString()]) {
        actionByMap[log.entityId.toString()] = log.userId ? log.userId.name : 'System';
      }
    });

    const invoiceMap = {};
    invoices.forEach(inv => {
      invoiceMap[inv._id.toString()] = inv;
    });

    dataList.forEach(item => {
      const invId = item.invoiceId.toString();
      const inv = invoiceMap[invId];
      item.uploadedBy = inv && inv.userId ? inv.userId.name : 'Unknown';
      item.status = inv ? inv.status : 'UNKNOWN';
      item.actionBy = actionByMap[invId] || 'N/A';
    });

    // 3. Define report title
    const shortType = type.split(' ')[0];
    const title = `${dateRange} ${type}`;
    const cleanTypeFilename = type.toLowerCase().replace(/[^a-z0-9]/g, '_');
    const timestamp = Date.now();
    const fileExtension = format === 'PDF' ? 'pdf' : 'csv';
    const filename = `report_${cleanTypeFilename}_${timestamp}.${fileExtension}`;
    
    const reportsDir = path.join(__dirname, '..', '..', 'uploads', 'reports');
    if (!fs.existsSync(reportsDir)) {
      fs.mkdirSync(reportsDir, { recursive: true });
    }
    const filePath = path.join(reportsDir, filename);
    const fileUrl = `/uploads/reports/${filename}`;

    // 4. Generate the physical file
    let fileBuffer;
    let sizeStr = '0 KB';
    if (format === 'PDF') {
      const pdfBytes = await generatePDFReport({
        title,
        type,
        dateRange,
        dataList,
        creatorName
      });
      fileBuffer = Buffer.from(pdfBytes);
      fs.writeFileSync(filePath, fileBuffer);
      sizeStr = `${(fileBuffer.length / (1024 * 1024)).toFixed(1)} MB`;
    } else {
      // CSV or XLSX
      const csvString = generateCSVReport({
        type,
        dateRange,
        dataList
      });
      fileBuffer = Buffer.from(csvString);
      fs.writeFileSync(filePath, fileBuffer);
      sizeStr = `${(fileBuffer.length / 1024).toFixed(1)} KB`;
    }

    // 5. Write to DB
    const newReport = await Report.create({
      title,
      type,
      format,
      dateRange,
      fileUrl,
      size: sizeStr,
      status: 'Ready',
      userId
    });

    res.status(201).json({ success: true, data: newReport });
  } catch (error) {
    next(error);
  }
};

// Delete report
const deleteReport = async (req, res, next) => {
  try {
    const { id } = req.params;
    const { role, _id: userId } = req.user;

    const report = await Report.findById(id);
    if (!report) {
      return res.status(404).json({ success: false, message: 'Report not found' });
    }

    // Authorization
    if (role === 'ACCOUNTANT' && report.userId.toString() !== userId.toString()) {
      return res.status(403).json({ success: false, message: 'Unauthorized' });
    }

    // Delete file
    const absolutePath = path.join(__dirname, '..', '..', report.fileUrl);
    if (fs.existsSync(absolutePath)) {
      fs.unlinkSync(absolutePath);
    }

    await Report.findByIdAndDelete(id);
    res.json({ success: true, message: 'Report deleted successfully' });
  } catch (error) {
    next(error);
  }
};

// Get Schedules
const getSchedules = async (req, res, next) => {
  try {
    const { role, _id: userId } = req.user;
    let filter = {};
    if (role === 'ADMIN' || req.user.approvalLevel >= 2) {
      const teamUserIds = await getTeamUserIds(req.user);
      filter.userId = { $in: teamUserIds };
    } else {
      filter.userId = userId;
    }
    const schedules = await ReportSchedule.find(filter).sort({ createdAt: -1 });
    res.json({ success: true, data: schedules });
  } catch (error) {
    next(error);
  }
};

// Create Schedule
const createSchedule = async (req, res, next) => {
  try {
    const { reportType, frequency, format, recipients } = req.body;
    const { _id: userId } = req.user;

    if (!reportType || !frequency || !format || !recipients) {
      return res.status(400).json({ success: false, message: 'All schedule fields are required.' });
    }

    const newSchedule = await ReportSchedule.create({
      reportType,
      frequency,
      format,
      recipients,
      userId
    });

    res.status(201).json({ success: true, data: newSchedule });
  } catch (error) {
    next(error);
  }
};

// Delete Schedule
const deleteSchedule = async (req, res, next) => {
  try {
    const { id } = req.params;
    const { role, _id: userId } = req.user;

    const schedule = await ReportSchedule.findById(id);
    if (!schedule) {
      return res.status(404).json({ success: false, message: 'Schedule not found' });
    }

    if (role === 'ACCOUNTANT' && schedule.userId.toString() !== userId.toString()) {
      return res.status(403).json({ success: false, message: 'Unauthorized' });
    }

    await ReportSchedule.findByIdAndDelete(id);
    res.json({ success: true, message: 'Schedule deleted successfully' });
  } catch (error) {
    next(error);
  }
};

module.exports = {
  getReports,
  generateReport,
  deleteReport,
  getSchedules,
  createSchedule,
  deleteSchedule
};
